### ISSUE TITLE
Propose to use Prettier 

### ISSUE THREAD

**Issue by bsoe003** [bote795/AniWrapper#21]
It would be nice to add [`prettier`](https://prettier.io/) to keep the coding style consistent and minimize lint errors.

* You can integrate `prettier` with `eslint`: https://github.com/prettier/eslint-config-prettier
* Create a formatter script either as an `npm` script or `eslint --fix` (https://github.com/prettier/prettier-eslint)

**Comment by bote795** [comment]
sure, would you want to put a pr? Does it autocorrect eslint issues, mainly?
